name: Build Aseprite on Intel Mac

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Aseprite版本号 (如v1.3.13)'
        required: true
        default: 'v1.3.13'

env:
  SKIA_VERSION: m102-861e4743af  # 与官方指定版本严格同步[1](@ref)
  BUILD_TYPE: RelWithDebInfo
  DEPLOYMENT_TARGET: '10.15'      # 提升最低兼容版本[1](@ref)
  SKIA_PATH: ${{ github.workspace }}/skia

jobs:
  build:
    runs-on: macos-13    # 加速依赖安装[1](@ref)
    strategy:
      matrix:
        arch: [x86_64]            # 强制Intel架构[1](@ref)

    steps:
      - name: 缓存构建文件
        uses: actions/cache@v3
        with:
          path: |
            build
            skia
          key: ${{ runner.os }}-${{ matrix.arch }}-${{ hashFiles('**/CMakeLists.txt') }}

      - name: 安装基础依赖
        run: |
          brew update --quiet
          brew install cmake ninja

      - name: 获取源码及子模块
        uses: actions/checkout@v4
        with:
          repository: aseprite/aseprite
          ref: ${{ github.event.inputs.version }}
          submodules: recursive    # 关键：获取skia子模块[1](@ref)

      - name: 配置Skia环境
        if: steps.cache.outputs.cache-hit != 'true'  # 缓存未命中时执行
        run: |
          SKIA_URL="https://github.com/aseprite/skia/releases/download/${{ env.SKIA_VERSION }}/Skia-macOS-Release-x64.zip"
          wget -q $SKIA_URL -O skia.zip
          unzip -q skia.zip -d skia
          echo "SKIA_PATH=$(pwd)/skia" >> $GITHUB_ENV

      - name: 生成构建配置
        run: |
          mkdir -p build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=${{ env.DEPLOYMENT_TARGET }} \
            -DSKIA_DIR=${{ env.SKIA_PATH }} \
            -DSKIA_LIBRARY_DIR=${{ env.SKIA_PATH }}/out/Release-x64 \
            -G Ninja

      - name: 编译二进制
        run: |
          cd build
          ninja -j4 aseprite  # 启用并行编译加速[3](@ref)

      - name: 生成带构建ID的便携包
        run: |
          cd build/bin
          zip -qr Aseprite-${{ github.event.inputs.version }}-b${{ github.run_id }}-macOS-Intel.zip \
            aseprite.app data

      - name: Upload release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/bin/Aseprite-${{ github.event.inputs.version }}-b${{ github.run_id }}-macOS-Intel.zip
          asset_name: Aseprite-${{ github.event.inputs.version }}-b${{ github.run_id }}-macOS-Intel.zip
          tag: ${{ needs.create-release.outputs.release-tag }}
