name: Build Aseprite on Intel Mac

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Aseprite版本号 (如v1.3.13)'
        required: true
        default: 'v1.3.13'

env:
  SKIA_VERSION: m102-861e4743af
  BUILD_TYPE: RelWithDebInfo
  DEPLOYMENT_TARGET: '10.15'
  SKIA_PATH: ${{ github.workspace }}/skia

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release-tag: ${{ steps.create-release.outputs.tag }}
    steps:
      - name: 生成唯一Release标签
        id: create-release
        run: |
          timestamp=$(date +%Y%m%d-%H%M%S)
          tag="build-${{ github.event.inputs.version }}-$timestamp"
          echo "tag=$tag" >> $GITHUB_OUTPUT

  build:
    runs-on: macos-13
    needs: [create-release]
    strategy:
      matrix:
        arch: [x86_64]

    steps:
      - name: 缓存构建文件
        uses: actions/cache@v3
        id: cache
        with:
          path: |
            build
            skia
          key: ${{ runner.os }}-${{ matrix.arch }}-${{ hashFiles('**/CMakeLists.txt') }}

      - name: 安装基础依赖
        run: |
          brew update --quiet
          brew install cmake ninja

      - name: 获取源码及子模块
        uses: actions/checkout@v4
        with:
          repository: aseprite/aseprite
          ref: ${{ github.event.inputs.version }}
          submodules: recursive

      - name: 配置Skia环境
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p skia
          SKIA_URL="https://github.com/aseprite/skia/releases/download/${{ env.SKIA_VERSION }}/Skia-macOS-Release-x64.zip"
          curl -L $SKIA_URL -o skia.zip
          unzip -q skia.zip -d skia
          rm skia.zip
          export laf_backend=skia

      - name: 生成构建配置
        run: |
          mkdir -p build && cd build
          cmake .. \
            -DCMAKE_BUILD_TYPE=${{ env.BUILD_TYPE }} \
            -DCMAKE_OSX_ARCHITECTURES=${{ matrix.arch }} \
            -DCMAKE_OSX_DEPLOYMENT_TARGET=${{ env.DEPLOYMENT_TARGET }} \
            -DSKIA_DIR=${{ env.SKIA_PATH }} \
            -DSKIA_LIBRARY_DIR=${{ env.SKIA_PATH }}/out/Release-x64 \
            -G Ninja

      - name: 编译二进制
        run: |
          cd build
          ninja aseprite -j $(sysctl -n hw.ncpu)

      - name: 生成便携包
        run: |
          cd build/bin
          zip -qr Aseprite-${{ github.event.inputs.version }}-${{ needs.create-release.outputs.release-tag }}-macOS-Intel.zip \
            aseprite.app data

      - name: 上传Release资产
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ needs.create-release.outputs.release-tag }}
          files: |
            build/bin/Aseprite-${{ github.event.inputs.version }}-${{ needs.create-release.outputs.release-tag }}-macOS-Intel.zip
